name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: master-thesis.tex
